require("basic")
require("colorScheme")
require("keybindings")
require("plugins")
require("color.material")
-- Plugins
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.nvim-treesitter")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.project")
-- LSP
require("lsp.setup")
require("lsp.cmp")
